"""empty message

Revision ID: 50c483035788
Revises: 
Create Date: 2021-06-17 15:24:27.546460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c483035788'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_manga', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('autor', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=80), nullable=True),
    sa.Column('nchap', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_manga')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recomendados',
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('genero', sa.String(length=80), nullable=False),
    sa.Column('editorial', sa.String(length=80), nullable=False),
    sa.Column('autor', sa.String(length=80), nullable=False),
    sa.Column('fecha_publicacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('titulo')
    )
    op.create_table('Lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_lista', sa.String(length=80), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_genero',
    sa.Column('mangaid', sa.Integer(), nullable=False),
    sa.Column('generoid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generoid'], ['Genero.id'], ),
    sa.ForeignKeyConstraint(['mangaid'], ['Manga.id'], ),
    sa.PrimaryKeyConstraint('mangaid', 'generoid')
    )
    op.create_table('lista_manga',
    sa.Column('listaid', sa.Integer(), nullable=False),
    sa.Column('mangaid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listaid'], ['Lista.id'], ),
    sa.ForeignKeyConstraint(['mangaid'], ['Manga.id'], ),
    sa.PrimaryKeyConstraint('listaid', 'mangaid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_manga')
    op.drop_table('manga_genero')
    op.drop_table('Lista')
    op.drop_table('recomendados')
    op.drop_table('User')
    op.drop_table('Manga')
    op.drop_table('Genero')
    # ### end Alembic commands ###
